version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crypto_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/db:/docker-entrypoint-initdb.d
    networks:
      - crypto-network

  api:
    build:
      context: .
      dockerfile: ./infra/docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/crypto_app?sslmode=disable
      - JWT_SECRET=your-super-secret-jwt-key
      - PORT=8080
    depends_on:
      - postgres
    networks:
      - crypto-network
    volumes:
      - ./apps/api:/app
    command: air -c .air.toml

  web:
    build:
      context: .
      dockerfile: ./infra/docker/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NODE_ENV=development
    depends_on:
      - api
    networks:
      - crypto-network
    volumes:
      - ./apps/web:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
    networks:
      - crypto-network

volumes:
  postgres_data:

networks:
  crypto-network:
    driver: bridge
